"""
    PhreeqcRM

Julia interface to the USGS PhreeqcRM reactive-transport reaction module.

PhreeqcRM is a stateful C++ object exposed via a flat C interface (`RM_*`). This
package provides two layers:

  - `PhreeqcRM.LibPhreeqcRM` — Clang.jl-generated `@ccall`s, one-to-one with the
    C header. Regenerated by maintainers from `gen/generator.jl`. Most users do
    not need it.
  - The top-level `PhreeqcRM.*` API — `PhreeqcRMInstance`, lifecycle methods,
    typed exceptions, per-domain unit `@enum`s, shape-validated concentration
    matrices, threading helpers. This is the documented surface.

See `deps/README.md` for building `libphreeqcrm` locally; the package looks for
it via `ENV["JULIA_PHREEQCRM_PATH"]` through the local `PhreeqcRM_jll` stub.
"""
module PhreeqcRM

# PhreeqcRM_jll is consumed transitively through LibPhreeqcRM (the generated
# bindings reference `PhreeqcRM_jll.libphreeqcrm`). Importing it here too
# keeps Aqua's stale-dependency check happy and makes the dep relationship
# explicit at the top of the package.
using PhreeqcRM_jll

include("LibPhreeqcRM.jl")
using .LibPhreeqcRM
const Lib = LibPhreeqcRM

include("errors.jl")
include("units.jl")
include("instance.jl")
include("components.jl")
include("concentrations.jl")
include("selected_output.jl")
include("transport.jl")
include("threading.jl")

export
    # Instance lifecycle
    PhreeqcRMInstance, with_instance,
    # Errors
    PhreeqcRMError, IRMResult,
    # Units
    SolutionUnits, PPAssemblageUnits, ExchangeUnits, SurfaceUnits,
    GasPhaseUnits, SSAssemblageUnits, KineticsUnits,
    # Database & input
    load_database!, run_file!, run_string!,
    # Components
    find_components!, components, ncomps, nxyz,
    # Spatial properties
    set_mapping!,
    set_porosity!, set_saturation!, set_representative_volume!,
    set_temperature!, set_pressure!, set_density!,
    set_units!,
    # Concentrations
    zeros_concentrations, set_concentrations!, get_concentrations, get_concentrations!,
    bycell,
    # Initial / boundary conditions
    set_initial_conditions!, initial_phreeqc_to_concentrations,
    # Time stepping
    set_time!, set_time_step!, run_cells!,
    # Output
    enable_selected_output!, get_selected_output, selected_output_headings,
    get_solution_volume, get_density, get_saturation,
    open_output!, close_output!,
    # Threading
    set_thread_count!, thread_count

end # module PhreeqcRM
